name: Test

on:
  - push
  - pull_request

jobs:
  tsc:
    name: Type Check

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node:
          - 14.1.0
        pnpm:
          - 4.11.1

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.vars.node }}
      - name: Cache PNPM store
        uses: actions/cache@v2.1.7
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
            pnpm-
      - name: Install pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: ${{ matrix.pnpm }}
          run_install: 'true'
      - name: Type Check
        run: |
          pnpm run test:tsc

  fmt:
    name: Code Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sane-fmt/action@0.11.0
        with:
          args: |
            - --details=diff
            - index.d.ts
            - index.js
            - test.ts
